spring.application.name=users-service

# Configuration of database PostrgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/volleyverseUsersdb
spring.datasource.username=postgres
spring.datasource.password=root

# Configuration of driver
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuration of JPA/Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update