spring.application.name=users-service

# Configuration of database PostrgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/volleyverseUsersdb
spring.datasource.username=postgres
spring.datasource.password=root

# Configuration of driver
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuration of JPA/Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=always

# Habilitar/deshabilitar api-docs swagger-ui
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

# definir la ruta de swagger-ui
springdoc.swagger-ui.path=/volleyverse-doc/swagger-ui.html

# Definir paquetes, clases a escanear
#springdoc.pakagesToScan=com.paquete1
springdoc.pathsToMatch=/volleyverse/api/**